name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Build and push Docker images
      env:
        PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      uses: docker/build-push-action@v1.1.0
      with:
        username: USERNAME
        password: PASSWORD
        repository: oldeesrock\magic-bean-brewing:brew-api
